### ISSUE TITLE
Extracting file fails with errors

### ISSUE THREAD

**Issue by ikrivosheev** [Lonami/lzxd#10]
Hello! Thank you for great library! 
I try to open cab archive using this library: https://github.com/mdsteele/rust-cab and get many errors:

```
w9xpopen.exe unpacker error=Custom { kind: Other, error: ChunkTooLong }
README.txt unpacker error=Custom { kind: Other, error: ChunkTooLong }
NEWS.txt unpacker error=Custom { kind: Other, error: OverreadBlock }
LICENSE.txt unpacker error=Custom { kind: Other, error: InvalidBlock(0) }
python.exe unpacker error=Custom { kind: Other, error: ChunkTooLong }
pythonw.exe unpacker error=Custom { kind: Other, error: ChunkTooLong }
python27.dll unpacker error=Custom { kind: Other, error: OverreadBlock }
...
```

File: [python.zip](https://github.com/Lonami/lzxd/files/8941886/python.zip)

Related issue: https://github.com/mdsteele/rust-cab/issues/14

**Comment by Lonami** [comment]
I haven't done much with this library in a fairly long time, and I currently can't work on solving this issue, but you're welcome to try! I'll gladly merge a pull request with a fix.

**Comment by ikrivosheev** [comment]
@Lonami thank you for the answer! Maybe can you give me link to RFC or something else? I will to resolve this problem.

**Comment by ikrivosheev** [comment]
Sorry, I find it)

**Comment by Lonami** [comment]
Wondering whether fixing #11 may have fixed this?

**Comment by ikrivosheev** [comment]
@Lonami hello! Maybe could you publish patch release?

**Comment by Lonami** [comment]
Probably didn't fix it. More investigation was done in the other issue linked from #11 though.

**Comment by Lonami** [comment]
0.2.0 is now on crates.io with a lot of work done from #8, so it's probably safe to close this as well.
