### ISSUE TITLE
How can bitstream::peek_bits work for bits > 16 ?

### ISSUE THREAD

**Issue by robinwatts** [Lonami/lzxd#11]
In the case where bits > 16, it calls:

            let lo = self.peek_bits_oneword(16) as u32;
            let hi = self.peek_bits_oneword(bits - 16) as u32;

But peek_bits_oneword doesn't change the bitsstream, so aren't you really peeking from the same point in the bitstream twice?

**Comment by Lonami** [comment]
Yeah you're right:

https://github.com/Lonami/lzxd/blob/ba70d7f8292ce840267b1ab89d44a9685c72ba1f/src/bitstream.rs#L128-L130

Seems to not be working as intended.

**Comment by robinwatts** [comment]
Apologies. I'm a rust newbie here, so maybe I'm missing something, but I can't see how that works either.

It looks to me like you're now consuming at least 16 bits from the stream. How is that equivalent to peeking?

**Comment by robinwatts** [comment]
Is it not implicit in the design of LZXD that codes can never be more than 16 bits, so we'll never need to peek more than 16 bits at a time?

**Comment by Lonami** [comment]
> I can't see how that works either

In https://github.com/Lonami/lzxd/commit/3fb190df8fa386ba6bd89ef5105fc2f6cf644f22 I clone the stream and first read, then peek. The first read consumes the bits and advances the cursor, so the second peek is at the right position. Spent some more time trying to think of alternatives but I don't have the brain for improvements today.

> Is it not implicit in the design of LZXD that codes can never be more than 16 bits

Been a long time since I read the LZXD spec, so I don't really remember a thing. If that's the case, then I guess all the logic to deal with more than 16 bits is dead code.

**Comment by robinwatts** [comment]
> In [3fb190d](https://github.com/Lonami/lzxd/commit/3fb190df8fa386ba6bd89ef5105fc2f6cf644f22) I clone the stream and first read, then peek. The first read consumes the bits and advances the cursor, so the second peek is at the right position. Spent some more time trying to think of alternatives but I don't have the brain for improvements today.

That makes perfect sense. I utterly failed to read the patch. Thanks.

> > Is it not implicit in the design of LZXD that codes can never be more than 16 bits
> 
> Been a long time since I read the LZXD spec, so I don't really remember a thing. If that's the case, then I guess all the logic to deal with more than 16 bits is dead code.

I could be wrong, as I've only been staring at the code, but I thought the implication was strong that path_lengths can never be more than 16.
