### ISSUE TITLE
Figuring out the equivalent of get_compressed_block() based on xnbcli is hard

### ISSUE THREAD

**Issue by jdm** [Lonami/lzxd#2]
This crate provides a single decompress_next method which accepts a slice. It's not clear to me how to obtain the chunks; the naive choice of `compressed.chunks(65_536)` doesn't work, but looking at https://github.com/LeonBlade/xnbcli/blob/ef55c383561addbd0bcfc11bfead6fc607502536/app/Presser/index.js#L21-L72 shows a different interface than lzxd provides.

**Comment by Lonami** [comment]
I'll update in a few hours how I parsed XNB files and maybe we can work out some additional documentation or examples, or a better interface. But what I did was parse a little bit of XNB manually before each chunk which comes with a kind of chunk size.

**Comment by Lonami** [comment]
I'm decompressing to `stdout` for simplicity of testing. After determining the compression type and reading the file size from the XNB file…

```rust
let file_size = cursor.read_u32();
let contents = match compression {
    Compression::Lzx => {
        let decompressed_size = cursor.read_u32();

        // XNB chunks in LZXD seem a bit odd? In theory a LZXD encoder prepends the
        // chunk length but with XNB we only need to read that if the first byte is 0xff.
        let mut lzxd = lzxd::Lzxd::new(WindowSize::KB64);
        loop {
            let (chunk_size, compressed_len) = if cursor.peek()[0] == 0xff {
                cursor.read_u8();
                (cursor.read_u16(), cursor.read_u16())
            } else {
                (32 * 1024, cursor.read_u16())
            };
            if compressed_len == 0 {
                break;
            }
            io::stdout().write_all(
                lzxd.decompress_next(cursor.read_slice(compressed_len as usize))
                    .unwrap(),
            );
        }
        _ => unimplemented!(),
};
```

The reason why this weird `cursor.peek()` for `0xff` is not inside the library itself is because I couldn't determine if this was part of LZXD itself or just some oddities in XNB. I'm inclined to say it's something weird with XNB and is not part of LZXD because I could not find any such weird checks in the LZXD reference.

**Comment by jdm** [comment]
Ok, that makes a bit more sense based on my reading of xbncli. Thanks!

**Comment by konkers** [comment]
I also started working on an xnb parsing library to parse Stardew Valley data files.   Here's where I'm handling the chunk parsing and decompression: https://github.com/konkers/xnb-rs/blob/main/src/lib.rs#L135

**Comment by jdm** [comment]
@konkers You may want to take a look at https://github.com/jdm/xnb-rs/.

**Comment by konkers** [comment]
Thanks @jdm.  I had a look an it looks like the API assumes you know the root object type in advance.  I was looking for something that would allow more generic operation and data exploration.

**Comment by Lonami** [comment]
If any of you can adapt this library to be flexible enough for your use case, please do send a pull request! I don't have enough domain knowledge on what you're working on to figure out what would be a good way to improve the ergonomics, so you're encouraged to become a contributor to this repository :)

**Comment by konkers** [comment]
I think the API is pretty good as is.  Adding the sample code you listed above to the docs or README might help people in the future.

**Comment by Lonami** [comment]
I'll close this for now, but feel free to send documentation improvements if there's still a need.
