### ISSUE TITLE
Chunk length must be divisible by 2

### ISSUE THREAD

**Issue by ikrivosheev** [Lonami/lzxd#21]
Hello! Thank you for the library. 
I got error: https://github.com/Lonami/lzxd/blob/master/src/lib.rs#L305

Sample: [python.gz](https://github.com/Lonami/lzxd/files/13661610/python.gz). 

Here is a file with name: `python275.chm`. Compressed size one of the block (block number is 1307) is: 32785. 

Here is lzx blocks: [python275.chm.tar.gz](https://github.com/Lonami/lzxd/files/13670561/python275.chm.tar.gz)
WindowSize is: MB2

Here is code to reproduce:

```rust
let mut pathes = std::fs::read_dir("/tmp/python275.chm").unwrap().map(|e| {
  let path = e.unwrap().path();
  let file_name = path.file_name().unwrap().to_str().unwrap().to_string();
  let parts = file_name.split(".").collect::<Vec<_>>();
  let idx = parts[3].parse::<usize>().unwrap();
  let compressed_size = parts[4].parse::<usize>().unwrap();
  let uncompressed_size = parts[5].parse::<usize>().unwrap();
  (path, idx, compressed_size, uncompressed_size)
}).collect::<Vec<_>>();

pathes.sort_by_key(|(_, idx, _, _)| *idx);

let mut lzxd = Lzxd::new(WindowSize::MB2);

for (path, idx, _, uncompressed_size) in pathes {
  let data = std::fs::read(path).unwrap();
  let res = lzxd.decompress_next(&data, uncompressed_size).unwrap();
  println!("{} - {}", idx, res.len())
}
```

**Comment by Lonami** [comment]
Thanks for the investigation. I haven't developed this library in a while, but your patch seemed reasonable, so I went ahead and merged it (although I haven't personally tested it).

**Comment by ikrivosheev** [comment]
@Lonami hello! Thank you for the merge, but my patch didn't fix the problem) 

I got the next error)

**Comment by Lonami** [comment]
Do you think we should revert the change then?

**Comment by ikrivosheev** [comment]
@Lonami I think, I can continue working on the issue. Maybe I will fix it)

**Comment by ikrivosheev** [comment]
@DrChat maybe do you have some thoughts?)

**Comment by ikrivosheev** [comment]
Hmm, maybe related to: 

1. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775499#8
2. https://github.com/kyz/libmspack/commit/18b6a2cc0b87536015bedd4f7763e6b02d5aa4f3

**Comment by ikrivosheev** [comment]
@Lonami can you publish release with this fix?

**Comment by Lonami** [comment]
Sure. [0.2.3](https://github.com/Lonami/lzxd/commit/65402c9e632047b04ce96eebd1da9b5b3d1898fe) should now be on crates.io.
