### ISSUE TITLE
Corrupted output if decompressed block is not padded to 32KB

### ISSUE THREAD

**Issue by DrChat** [Lonami/lzxd#7]
I have a cabinet file here with a single file called `blob` that is compressed using `LZX`.
Using `rust-cab` - I can just about successfully decompress this file and access it.

However, at the very end of the file, it is evident that decompression is beginning to break down and fail:
```xml
⁮/CategoreType="Pr摯P捵ot" Prshabst Su换Categories="true"\Ex汣<摵le䉤T Default="falss" xmlns:cat="http://schemas.microsoft.com/msus/2002/12/UpdateHandlers/Category" />⼼<upd:Handle卲uiecffi䑣dat/>⼼<upd:Updat/
```

From some debugging output I put in `lzxd` - it seems that this corruption corresponds to the second decoded block. Looking at the output from the sliding window, perhaps it's a simple off-by-one error that is being compounded by the sliding window?

These are the bytes output at the end of decompression, (inexactly) corresponding with the above text:
```
572: [00, 2F, 00, 3E, 00, 3C, 2F]
579: [3C, 00, 75, 00, 70, 00, 64, 00, 3A, 00, 48, 00, 61, 00, 6E, 00, 64, 00, 6C, 00, 65, 00, 72, 53, 75, 00, 69, 00, 65, 00, 63, 00, 66, 00, 66, 00, 69, 00, 63, 44, 64, 00, 61, 00, 74, 00]
5A7: [2F, 00, 3E, 00, 3C, 2F, 3C, 00, 75, 00, 70, 00, 64, 00, 3A]
5B6: [00, 55, 00, 70, 00, 64, 00, 61, 00, 74, 00]
5C1: [2F, 00, 3E]
```
The format is UTF-16 LE, and the text lies within the ASCII character set, so every other byte should be `0x00`.

At the beginning of the second block, you can see it start outputting invalid UTF-16:
```
101: [41, 00, 43, 00, 48, 00, 49, 00, 4E, 00, 45, 00, 22, 00, 20, 00, 53, 00, 75, 00, 62, 00, 6B, 00, 65, 00, 79, 00, 3D, 00, 22, 00, 53, 00, 4F, 00, 46, 00, 54, 00, 57, 00, 41, 00, 52, 00, 45, 00, 5C, 00, 4D, 00, 69, 00, 63, 00, 72, 00, 6F, 00, 73, 00, 6F, 00, 66, 00, 74, 00, 5C, 00, 4F, 00, 66, 00, 66, 00, 69, 00, 63, 00, 65, 00, 5C, 00, 31]
156: [30] <--------------- should be 00!
157: [31, 00, 2E, 00, 30, 00, 5C, 00, 50, 00, 6F, 00, 77, 00, 65, 00, 72, 00, 50, 00, 6F, 00, 69, 00, 6E, 00, 74, 00, 5C, 00, 49, 00, 6E, 00, 73, 00, 74, 00, 61, 00, 6C, 00, 6C, 00, 52, 00, 6F, 00, 6F, 00, 74, 00, 22, 00, 20, 00, 52, 00, 65, 00, 67, 00, 54, 00, 79, 00, 70, 00, 65, 00, 33, 00, 32, 00, 3D, 00, 22, 00, 74, 00, 72, 00, 75, 00, 65, 00, 22, 00, 20, 00, 78, 00, 6D, 00, 6C, 00, 6E, 00, 73, 00, 3A, 00, 62, 00, 61, 00, 72, 00, 3D, 00, 22, 00, 68, 00, 74, 00, 74, 00, 70, 00, 3A, 00, 2F, 00, 2F, 00, 73, 00, 63, 00, 68, 00, 65, 00, 6D, 00, 61, 00, 73, 00, 2E, 00, 6D, 00, 69, 00, 63, 00, 72, 00, 6F, 00, 73, 00, 6F, 00, 66, 00, 74, 00, 2E, 00, 63, 00, 6F, 00, 6D, 00, 2F, 00, 6D, 00, 73, 00, 75, 00, 73, 00, 2F, 00, 32, 00, 30, 00, 30, 00, 32, 00, 2F, 00, 31, 00, 32, 00, 2F, 00, 42, 00, 61, 00, 73, 00, 65, 00, 41, 00, 70, 00, 70, 00, 6C, 00, 69, 00, 63, 00, 61, 00, 62, 00, 69, 00, 6C, 00, 69, 00, 74, 00, 79, 00, 52, 00, 75, 00, 6C, 00, 65, 00, 73, 00, 22, 00, 20, 00, 2F, 00, 3E, 00, 3C]
250: [2F] <--------------- should be 00!
251: [3C, 00, 6C, 00, 61, 00, 72, 00, 3A, 00, 4F, 00, 72]
25E: [00, 3E, 00, 3C, 2F]
```

I'll document more as I figure it out in this issue.

**Comment by DrChat** [comment]
Decode history at the point between the two blocks:
```
7F4A: Match { offset: 404, length: 120 }
7FC2: Single(49)
7FC3: Match { offset: 404, length: 60 } <------------ goes from 0x7FC3 to 0x7FFF, one less than the uncompressed block size
0: Match { offset: 404, length: 257 }
101: Match { offset: 404, length: 85 }
156: Single(48)
157: Match { offset: 404, length: 249 }
250: Single(47)
```

**Comment by DrChat** [comment]
Artificially padding the window with zeros to match the uncompressed block size fixes the bug.

I inserted the following snippet of code into `decompress_next`, shortly before calling `Self::postprocess`.
```rust
        // FIXME: Why is the last block's size observed to be one?
        if self.current_block.size > 1 {
            // If we aren't finished decoding, align the window up to 32KB.
            if let Some(len) = 0x8000usize.checked_sub(decoded_len) {
                decoded_len += len;

                for _ in 0..len {
                    self.window.push(0);
                }
            }
        }
```

**Comment by Lonami** [comment]
If I'm understanding correctly, would resetting the window to all-zero before reading from the bitstream also work?

**Comment by DrChat** [comment]
I don't quite understand - do you mean zeroing the entire sliding window upon entry or exit to `decompress_next`?

**Comment by Lonami** [comment]
Yes, upon entry (I would've tried myself, but I don't have access to the file).

**Comment by DrChat** [comment]
[broken.zip](https://github.com/Lonami/lzxd/files/7273502/broken.zip)

Here's the file attached - meant to attach it earlier but GitHub doesn't allow .cab files directly.
To decompress the file, use [`rust-cab`](https://github.com/mdsteele/rust-cab):
```
$ cargo run --example cabtool -- cat broken.cab blob > blob
```

**Comment by Lonami** [comment]
I've tried my "idea" of clearing the buffer before doesn't work (it's kind of a dumb idea looking back). I've gone ahead and added your patch (without the FIXME, and a somewhat hopefully micro-optimized version) for the time being but we can still make changes to it if need be.

**Comment by DrChat** [comment]
Thanks!

**Comment by DrChat** [comment]
Oh, P.S: Could you kick off a new version on crates.io?
Someone actually hit a crash that I fixed here recently in `rust-cab`.

**Comment by Lonami** [comment]
I've published 0.1.3 to crates.io. However, I would still like to learn why https://github.com/Lonami/lzxd/commit/b7e5b4b8b369fe94ec7d9f54cb307320f9bc8649 fixes it before closing this, or where in the specification this "quirk" is documented. I don't recall seeing it before.

**Comment by DrChat** [comment]
I agree - I couldn't confirm why this behavior resulted in correct operation.
I only knew from documentation that the output size of each block is exactly 32KB - and padding the size to 32KB seemingly fixed the incorrect behavior I've been seeing.

**Comment by Lonami** [comment]
I may need to give the spec another read, and maybe email the Microsoft team about this if I can't find any clues, they seemed helpful last time. By the way, thanks for the help with the project. I should spend some time reading up on compression algorithms.

**Comment by DrChat** [comment]
Sounds good! And no worries, this project has been plenty educational for me too.
Thanks for making it!

**Comment by DrChat** [comment]
Oh - oops! It looks like your change will pad the size of a decompressed chunk up to 32kb, even if it's the last block!
Can you add a check before padding it to ensure that it's not the last block?

**Comment by Lonami** [comment]
Is it necessary that it is not the last block? I removed it because I (wrongly) assumed the "current block size > 1" was a temporary workaround until we figured the proper solution. I tried it without the check on your data and it worked (but it probably was too small to be meaningful).

**Comment by DrChat** [comment]
Hmm... well, I'm not terribly sure. From my testing, the block size check worked out better.
But the padding in its current form breaks the `rust-cab` test I added for LZX-compressed archives.

**Comment by DrChat** [comment]
👍 Thanks! I confirmed that the `rust-cab` test is working with `lzxd = "0.1.4"`.
One of my projects has to process a large number of LZXD-compressed cabinet files, so I'm going to continue stress-testing LZXD and shuffling out bugs as they come.

**Comment by Lonami** [comment]
I'm guessing this is safe to close after your work?

**Comment by DrChat** [comment]
I would assume so - I haven't tried to reproduce this issue.
It might be worth setting up decompression tests with test data including this as well as the renderdoc PDB. I was briefly looking at that but I'm not sure of the best way to include the data (outside of using `git-lfs`).

**Comment by Lonami** [comment]
Yeah having more tests would be smart. Maybe a subrepository with the files could do. Just need to make sure we use files that are safe to host.

**Comment by DrChat** [comment]
@Lonami Due to some [silly reasoning](https://docs.github.com/en/repositories/working-with-files/managing-large-files/collaboration-with-git-large-file-storage#pushing-large-files-to-forks), looks like I cannot create a PR with LFS objects without having push access to this repository.
Would you be able to grant me contributor access?

**Comment by Lonami** [comment]
Invite sent https://github.com/Lonami/lzxd/invitations.

**Comment by Lonami** [comment]
> Due to some [silly reasoning](https://docs.github.com/en/repositories/working-with-files/managing-large-files/collaboration-with-git-large-file-storage#pushing-large-files-to-forks)

Ah, this email I received today might explain it:

> We wanted to let you know that you’ve used 80% of your data plan for Git LFS on your personal account Lonami. No immediate action is necessary, but you might want to consider purchasing additional data packs to cover your bandwidth and storage usage:
> 
>   https://github.com/account/billing/data/upgrade
> 
> Current usage as of 03 Dec 2023 06:59PM UTC:
> 
>   Bandwidth: 0.81 GB / 1 GB (81%)
>   Storage: 0.13 GB / 1 GB (13%)

**Comment by DrChat** [comment]
Oh wow, that is a small limit haha.

**Comment by Lonami** [comment]
Today GitHub decided I've hit 1GB despite not pushing anything this large that I'm aware of, wut:

> You’ve used 100% of your data plan for Git LFS [...]
> Bandwidth: 1.04 GB / 1 GB (104%)
> Storage: 0.13 GB / 1 GB (13%)

**Comment by DrChat** [comment]
Huh, that seems to be a rather poorly thought out limit.
If you push 1GB of content, then downloading it once is enough to blow past the bandwidth limit.
Ugh....

**Comment by Lonami** [comment]
It seems like I can no longer publish the package with the new test data introduced by #19:

```
$ cargo publish
    Updating crates.io index
   Packaging lzxd v0.2.2 (C:\Users\L\Documents\Projects\lzxd)
   Verifying lzxd v0.2.2 (C:\Users\L\Documents\Projects\lzxd)
   Compiling lzxd v0.2.2 (C:\Users\L\Documents\Projects\lzxd\target\package\lzxd-0.2.2)
    Finished dev [unoptimized + debuginfo] target(s) in 22.42s
    Packaged 17 files, 137.7MiB (47.0MiB compressed)
   Uploading lzxd v0.2.2 (C:\Users\L\Documents\Projects\lzxd)
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error: max upload size is: 10485760

$ ls "target\package\lzxd-0.2.2"
Cargo.toml  Cargo.toml.orig  LICENSE-APACHE  LICENSE-MIT  README.md  src/  target/  testdata/  tests/
```

Might need to revert that. Thoughts?

**Comment by DrChat** [comment]
Oh, dang - I hadn't thought of that.
Hmm, does cargo have an ignore file we could check in?

**Comment by Lonami** [comment]
Yeah [`exclude`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) seems to do it (https://github.com/Lonami/lzxd/commit/9df61c7d2f0f7f132296d360f284bd34e9a98419). I'll also close this issue, since this should've been fixed.
