### ISSUE TITLE
Extracting this renderdoc.pdb.cab fails with InvalidBlock(4)

### ISSUE THREAD

**Issue by mstange** [Lonami/lzxd#8]
Here's [a cab file](https://renderdoc.org/symbols/renderdoc.pdb/6D1DFFC4DC524537962CCABC000820641/renderdoc.pd_) which `cabextract` can uncompress successfully, but [the `cab` crate](https://github.com/mdsteele/rust-cab) fails on:

```
% curl -o renderdoc.pdb.cab "https://renderdoc.org/symbols/renderdoc.pdb/6D1DFFC4DC524537962CCABC000820641/renderdoc.pd_"
% cargo install --examples cab
% cabtool cat renderdoc.pdb.cab renderdoc.pdb > renderdoc.pdb
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: InvalidBlock(4) }', /Users/mstange/.cargo/registry/src/github.com-1ecc6299db9ec823/cab-0.3.0/examples/cabtool.rs:64:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Lonami** [comment]
Oh, `cab` has started depending on this crate. That explains the increase in interest. Maybe now I actually need to commit more time to this project I thought little people used. Pull requests are always welcome too!

**Comment by Lonami** [comment]
Repro code:

```rust
use std::io::{Cursor, Read};

const LZXD: &[u8] = include_bytes!("renderdoc.pd_");

fn main() {
    let mut buf = Vec::new();
    let mut cabinet = cab::Cabinet::new(Cursor::new(LZXD)).unwrap();
    cabinet.read_file("renderdoc.pdb").unwrap().read_to_end(&mut buf).unwrap();
}
```

**Comment by Lonami** [comment]
[`cabextract`](https://www.cabextract.org.uk/) makes use of [`libmspack`](https://www.cabextract.org.uk/libmspack/) underneath, but I've taken a look at the header files and [there's no such block 4](https://github.com/kyz/libmspack/blob/a0dfb6922d86c3f2aa8e584ff558d3244dd40d66/libmspack/mspack/lzx.h#L26-L29). This makes me think we may be messing up earlier in the decoding process:

**Comment by DrChat** [comment]
```
Block kind: 0x2, size: 305485
Block kind: 0x2, size: 239736
Block kind: 0x2, size: 258852
Block kind: 0x2, size: 236972
Block kind: 0x2, size: 266186
Block kind: 0x2, size: 278051
Block kind: 0x4, size: 11176320
```

Interestingly, the block before the corruption is encountered is an odd-sized length.

**Comment by Lonami** [comment]
The first block is also odd-sized. To rule out weird off-by-one errors, I tried to bump the size by one when the size is 278051 (it failed with "overread") and lower it by one (it failed with the next block kind being 0x5). Quite strange.

Would probably be a good idea to get full test coverage. Maybe if we exercise all branches in the code it would be enough to rule out problems like this one.

**Comment by DrChat** [comment]
Agreed wrt test coverage. I was hoping at some point to create an automatic test that used a fuzzer + `makecab` and `lzxd` to compress and decompress a file and ensure that the contents are correct.

It may be doable nowadays, `cargo-fuzz` works on Windows now iirc.

**Comment by Lonami** [comment]
Wondering whether fixing #11 may have fixed this?

**Comment by DrChat** [comment]
Seemingly not, still seeing a repro on `master`.

Did some more digging, seems to be corruption in the preceding block:
```
0x0018307E: Single(1)
0x0018307F: Single(3)
0x00183080: Single(68)
0x00183081: Single(5)
0x00183082: Single(6) <---------------- bad! should be 0xF4
0x00183083: Single(1)
0x00183084: Single(220)
0x00183085: Single(45)
0x00183086: Single(72)
Block kind: 0x4, size: 11176320
```

![image](https://github.com/Lonami/lzxd/assets/2402369/5e54ba70-3d90-4560-86fe-3e910091fb50)

**Comment by DrChat** [comment]
Additionally, seems that the E8 translation is broken from comparing the good baseline with the one produced by this library.

So I'm actually at a loss as to why element decoding goes off the rails at the point that it does. All the code I've been poking around at seems like it's working properly (bitstreams, trees).
Forcibly changing the `code` in `Tree::decode_element` to `0xF4` doesn't put things back on track either.

**Comment by DrChat** [comment]
Seems to be an off-by-five? If I subtract the previous block's size by 5, decoding continues on and the file bytes I highlighted above are correctly outputted by `lzxd`.
Could be related to E8 translation, given that that affects exactly 5 bytes at a time.

**Comment by DrChat** [comment]
Alright, figured it out. The zero-extension logic here does not subtract the additional bytes from `self.current_block.size` (which represents the _decompressed_ size).

https://github.com/Lonami/lzxd/blob/3fb190df8fa386ba6bd89ef5105fc2f6cf644f22/src/lib.rs#L342-L345

_However_, with this bug fixed, it seems that there is an additional bug still preventing the Chrome symbols from being decompressed.

**Comment by Lonami** [comment]
Thanks a lot for the thorough investigation.

**Comment by DrChat** [comment]
Opened #12 for that one.

I'm now seeing this failure:
```
decompress_next: chunk_offset = 0x1670000, len=1158
decompress_next: chunk_offset = 0x1678000, len=1168
decompress_next: chunk_offset = 0x1680000, len=1162
decompress_next: chunk_offset = 0x1688000, len=7288
decompress_next: chunk_offset = 0x1690000, len=6882
decompress_next: chunk_offset = 0x1698000, len=13702
Block kind: 0x1, size: 10233
thread 'main' panicked at examples\cabtool.rs:67:54:
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: InvalidPathLengths }
```

~~It's likely another misalignment issue - every block emitted was type `0x2` (aligned offset tree) thus far in the file so it makes no sense for block `0x1` (verbatim tree) to suddenly be emitted.~~

Not a misalignment. The length tree's path lengths are all `0`, and that is allowed per `lzxd.c`:
https://github.com/kyz/libmspack/blob/305907723a4e7ab2018e58040059ffb5e77db837/libmspack/mspack/lzxd.c#L555-L558

**Comment by DrChat** [comment]
Opened #13. Looks like decompression is now successful (except for `E8` decoding, which is still broken)

**Comment by DrChat** [comment]
Opened #14 to address `E8` decoding. There is still one more unknown bug causing differences between the reference file I have and the one output by `lzxd`.

Seems to be related to the padding bytes.
For some reason, the reference file has nonzero padding bytes in some cases where we emit zeroes. No misalignment or anything else though, so that's weird...

**Comment by DrChat** [comment]
Looks like there is no such thing as padding per the LZX file format, so this block needs to go:
https://github.com/Lonami/lzxd/blob/3fb190df8fa386ba6bd89ef5105fc2f6cf644f22/src/lib.rs#L339-L346

1) Output chunk size should be provided by our caller, and we should attempt to continue decoding until we output that number of bytes. This is what the C implementation of LZX does (i.e. `while !bitstream.is_empty()` -> `while decoded_len != output_len`).
2) `Bitstream::is_empty` seems to be wrong? Regardless, this is irrelevant once the above is done and can be removed.

I created #15 to fix this.

Now there's (still, _ugh_) some other unknown issue causing differences between my reference file and `lzxd`'s output.

**Comment by DrChat** [comment]
For the (hopefully last) mismatch, at file offset 0x752A03A it would seem that the match offset decoding is busted for verbatim blocks.
Specifically, the match offset _should_ be `0x673D4`. It is actually `0x639E9`. That is a difference of `0x39EB`, which is exactly the value of `verbatim_bits`.

In other words, it would imply that `verbatim_bits` is half of what it should be.

**Comment by DrChat** [comment]
![image](https://github.com/Lonami/lzxd/assets/2402369/c2ae8570-b08b-4190-a8e4-cd702e30471b)

🎉🎉🎉🎉 I did it!!!!!

The last bug was an endianness issue with `read_bits` when reading more than one word.
https://github.com/Lonami/lzxd/blob/3fb190df8fa386ba6bd89ef5105fc2f6cf644f22/src/bitstream.rs#L89-L93

This should be:
```
            // Read the two words.
            let w0 = self.read_bits_oneword(16)? as u32;
            let w1 = self.read_bits_oneword(bits - 16)? as u32;

            Ok((w0 << (bits - 16)) | w1)
```

#16

**Comment by Lonami** [comment]
Absolutely tremendous amount of work @DrChat. Thank you so much. I'll release a new version after addressing https://github.com/Lonami/lzxd/pull/13#issuecomment-1817679964, hopefully shortly.

**Comment by DrChat** [comment]
Awesome, thanks!

**Comment by mstange** [comment]
Fantastic, thanks so much for your work!

**Comment by Lonami** [comment]
lzxd 0.2 is now on crates.io, and it should be safe to close this.
